openapi: 3.0.2
info:
  title: PubChemIndex
  version: 1.0.0
servers:
- url: /
tags:
- name: molecule
paths:
  /ingestion:
    get:
      operationId: ingest
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: ok
      x-openapi-router-controller: pub_chem_index.controllers.default_controller
  /molecules:
    description: The REST endpoint/path used to list and create zero or more `Molecule`
      entities.  This path contains a `GET` and `POST` operation to perform the list
      and create tasks, respectively.
    get:
      description: Gets a list of all `Molecule` entities.
      operationId: get_molecules
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Molecule'
                type: array
          description: Successful response - returns an array of `Molecule` entities.
      summary: List All Molecules
      tags:
      - molecule
      x-openapi-router-controller: pub_chem_index.controllers.molecule_controller
    summary: Path used to manage the list of molecules.
  /molecules/{moleculeByCID}:
    description: The REST endpoint/path used to get single instances of an `Molecule`.  This
      path contains `GET` operations used to perform the get tasks, respectively.
    get:
      description: Gets the details of a single instance of a `Molecule`.
      operationId: get_molecule_by_cid
      parameters:
      - description: A unique identifier for a `Molecule`.
        explode: false
        in: path
        name: moleculeByCID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Molecule'
          description: Successful response - returns a single `Molecule`.
      summary: Get a Molecule
      tags:
      - molecule
      x-openapi-router-controller: pub_chem_index.controllers.molecule_controller
    summary: Path used to manage a single Molecule search by CID.
  /molecules/{moleculeBySynonym}:
    description: The REST endpoint/path used to get single instances of an `Molecule`.  This
      path contains `GET` operations used to perform the get tasks, respectively.
    get:
      description: Gets the details of a single instance of a `Molecule`.
      operationId: get_molecule_by_synonym
      parameters:
      - description: A unique identifier for a `Molecule`.
        explode: false
        in: path
        name: moleculeBySynonym
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Molecule'
          description: Successful response - returns a single `Molecule`.
      summary: Get Molecules by synonym.
      tags:
      - molecule
      x-openapi-router-controller: pub_chem_index.controllers.molecule_controller
    summary: Path used to manage a single Molecule search by synonym.
components:
  schemas:
    Molecule:
      description: List of synonyms matching search query
      example:
        search: search
        synonyms:
        - synonyms
        - synonyms
      properties:
        search:
          title: search
          type: string
        synonyms:
          description: List of synonyms matching search query
          items:
            type: string
          title: synonyms
          type: array
      required:
      - search
      - synonyms
      title: Molecule
      type: object
