"""
    PubChemIndex

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cloudharness_cli.pub_chem_index
from cloudharness_cli.pub_chem_index.model.molecule import Molecule


class TestMolecule(unittest.TestCase):
    """Molecule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMolecule(self):
        """Test Molecule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Molecule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
