"""
    PubChemIndex

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import cloudharness_cli.pub_chem_index
from cloudharness_cli.pub_chem_index.api.molecule_api import MoleculeApi  # noqa: E501


class TestMoleculeApi(unittest.TestCase):
    """MoleculeApi unit test stubs"""

    def setUp(self):
        self.api = MoleculeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_molecule(self):
        """Test case for create_molecule

        Create a Molecule  # noqa: E501
        """
        pass

    def test_delete_molecule(self):
        """Test case for delete_molecule

        Delete a Molecule  # noqa: E501
        """
        pass

    def test_get_molecule(self):
        """Test case for get_molecule

        Get a Molecule  # noqa: E501
        """
        pass

    def test_get_molecules(self):
        """Test case for get_molecules

        List All Molecules  # noqa: E501
        """
        pass

    def test_update_molecule(self):
        """Test case for update_molecule

        Update a Molecule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
