harness:
  subdomain: pubchem
  secured: false
  service:
    port: 8080
    auto: true

  database:
    type: postgres
    auto: true
    name: pubchem-db
    image_ref: pubchem-postgres
    size: 100Gi
  deployment:
    auto: true
    port: 8080
    volume:
      auto: false
      size: 10Gi
      create: false
      name: pubchem-db
      mountpath: /data/db
  dependencies:
    build:
      - cloudharness-base
      - cloudharness-flask
      - pubchem-postgres
    soft:
    - argo