harness:
  subdomain: pubchem
  secured: false
  service:
    port: 8080
    auto: true

  database:
    type: postgres
    auto: true
    name: pubchem-db
    image_ref: pubchem-postgres
    size: 100Gi
    resources:
      requests:
        memory: 8192Mi
        cpu: 2
      limits:
        memory: 32768Mi
        cpu: 2
  deployment:
    auto: true
    port: 8080
  dependencies:
    build:
      - cloudharness-base
      - cloudharness-flask
      - pubchem-postgres
    soft:
    - argo