harness:
  subdomain: pubchem
  secured: false
  service:
    port: 8080
    auto: true

  database:
    type: postgres
    auto: true
    name: pubchem-db
    image_ref: pubchem-postgres
    size: 240Gi
    resources:
      requests:
          memory: 8Gi
          cpu: 1
      limits:
        memory: 8Gi
        cpu: 1
    args: ["--vm", "1", "--vm-bytes", "8Gi", "--vm-hang", "1"]
  deployment:
    auto: true
    port: 8080
  dependencies:
    build:
      - cloudharness-base-debian
      - cloudharness-flask
      - pubchem-postgres
    soft:
    - argo