harness:
  subdomain: pubchem
  secured: false
  service:
    port: 8080
    auto: true

  database:
    type: postgres
    auto: true
    postgres:
      image: pubchem-postgres:latest
  deployment:
    auto: true
    port: 8080
  dependencies:
    build:
      - cloudharness-base
      - cloudharness-flask
      - pubchem-postgres