openapi: 3.0.2
info:
  title: PubChemIndex
  version: 1.0.0
paths:
  /molecules:
    summary: Path used to manage the list of molecules.
    description: >-
      The REST endpoint/path used to list and create zero or more `Molecule` entities.  This path
      contains a `GET` and `POST` operation to perform the list and create tasks, respectively.
    get:
      tags:
        - molecule
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Molecule"
          description: Successful response - returns an array of `Molecule` entities.
      operationId: getMolecules
      summary: List All Molecules
      description: Gets a list of all `Molecule` entities.
  "/molecules/{term}":
    summary: Path used to manage a single Molecule search by CID.
    description: >-
      The REST endpoint/path used to get single instances of an `Molecule`.  This
      path contains `GET` operations used to perform the get tasks, respectively.
    get:
      tags:
        - molecule
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Molecule"
          description: Successful response - returns a single `Molecule`.
      operationId: searchMolecules
      summary: Get a Molecule
      description: Gets the details of a single instance of a `Molecule`.
    parameters:
      - name: term
        description: A unique identifier for a `Molecule`.
        schema:
          type: string
        in: path
        required: true
  /ingestion:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: ok
      operationId: ingest
components:
  schemas:
    Molecule:
      description: "List of synonyms matching search query"
      required:
        - synonyms
      type: object
      properties:
        synonyms:
          description: "List of synonyms matching search query"
          type: array
          items:
            type: string
tags:
  - name: molecule
    description: ""
